"""Add invite tracking fields to User and InviteCode models

Revision ID: 0e2ad4779bba
Revises: 687f5c4e327a
Create Date: 2025-05-06 01:49:41.040943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2ad4779bba'
down_revision = '687f5c4e327a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('used_invite_code_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_used_invite_code_id'), ['used_invite_code_id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_invited_by_user_id'), 'user', ['invited_by_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_used_invite_code_id'), 'invite_code', ['used_invite_code_id'], ['id'])
        batch_op.drop_column('used_invite_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_invite_code', sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_used_invite_code_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_invited_by_user_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_user_used_invite_code_id'), type_='unique')
        batch_op.drop_column('used_invite_code_id')
        batch_op.drop_column('invited_by_user_id')

    # ### end Alembic commands ###
