"""Add Ampersound model

Revision ID: 0f2addf57b0f
Revises: b9f1d7f3368c
Create Date: 2025-05-06 04:41:32.580011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2addf57b0f'
down_revision = 'b9f1d7f3368c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ampersound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_ampersound_name')
    )
    with op.batch_alter_table('ampersound', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ampersound_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ampersound', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ampersound_timestamp'))

    op.drop_table('ampersound')
    # ### end Alembic commands ###
