"""Add score to Post model, remove PostCategoryScore

Revision ID: 2264d7975933
Revises: 0d6731c4b557
Create Date: 2025-05-03 20:02:58.458064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2264d7975933'
down_revision = '0d6731c4b557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_category_score', schema=None) as batch_op:
        batch_op.drop_index('ix_post_category_score_category')

    op.drop_table('post_category_score')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_score'), ['score'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_score'))
        batch_op.drop_column('score')

    op.create_table('post_category_score',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'category', name='uq_post_category_score')
    )
    with op.batch_alter_table('post_category_score', schema=None) as batch_op:
        batch_op.create_index('ix_post_category_score_category', ['category'], unique=False)

    # ### end Alembic commands ###
