"""add report system, user types, and comment visibility

Revision ID: 368efc70cad6
Revises: 5a687c4bd593
Create Date: 2025-05-06 08:48:09.362432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368efc70cad6'
down_revision = '5a687c4bd593'
branch_labels = None
depends_on = None

# Enum definitions (values must match models.py and raw SQL below)
_COMMENT_VISIBILITY_VALUES = ('PUBLIC', 'FRIENDS_ONLY', 'HIDDEN')
_USER_TYPE_VALUES = ('USER', 'ADMIN')
_REPORT_CONTENT_TYPE_VALUES = ('POST', 'COMMENT', 'AMPERSOUND')
_REPORT_STATUS_VALUES = ('PENDING', 'RESOLVED_AUTO', 'RESOLVED_MANUAL', 'DISMISSED')

comment_visibility_enum_fordrop = sa.Enum(*_COMMENT_VISIBILITY_VALUES, name='commentvisibility')
user_type_enum_fordrop = sa.Enum(*_USER_TYPE_VALUES, name='usertype')
report_content_type_enum_fordrop = sa.Enum(*_REPORT_CONTENT_TYPE_VALUES, name='reportcontenttype')
report_status_enum_fordrop = sa.Enum(*_REPORT_STATUS_VALUES, name='reportstatus')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Explicitly create ENUM types for PostgreSQL using raw SQL with IF NOT EXISTS
    op.execute(f"DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'commentvisibility') THEN CREATE TYPE commentvisibility AS ENUM {str(_COMMENT_VISIBILITY_VALUES)}; END IF; END $$;")
    op.execute(f"DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'usertype') THEN CREATE TYPE usertype AS ENUM {str(_USER_TYPE_VALUES)}; END IF; END $$;")
    op.execute(f"DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reportcontenttype') THEN CREATE TYPE reportcontenttype AS ENUM {str(_REPORT_CONTENT_TYPE_VALUES)}; END IF; END $$;")
    op.execute(f"DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reportstatus') THEN CREATE TYPE reportstatus AS ENUM {str(_REPORT_STATUS_VALUES)}; END IF; END $$;")

    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reported_user_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum(*_REPORT_CONTENT_TYPE_VALUES, name='reportcontenttype', create_type=False), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum(*_REPORT_STATUS_VALUES, name='reportstatus', create_type=False), server_default='PENDING', nullable=False),
    sa.ForeignKeyConstraint(['reported_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'content_type', 'content_id', name='uq_report_once_per_content')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.Enum(*_COMMENT_VISIBILITY_VALUES, name='commentvisibility', create_type=False), nullable=True))
    
    op.execute("UPDATE comment SET visibility = 'PUBLIC' WHERE visibility IS NULL")
    
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('visibility', existing_type=sa.Enum(*_COMMENT_VISIBILITY_VALUES, name='commentvisibility', create_type=False), nullable=False, server_default='PUBLIC')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.Enum(*_USER_TYPE_VALUES, name='usertype', create_type=False), nullable=True))

    op.execute("UPDATE \"user\" SET user_type = 'USER' WHERE user_type IS NULL")
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_type', existing_type=sa.Enum(*_USER_TYPE_VALUES, name='usertype', create_type=False), nullable=False, server_default='USER')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_timestamp'))

    op.drop_table('report')

    # Drop ENUM types for PostgreSQL - using the specific instances for clarity
    bind = op.get_bind()
    comment_visibility_enum_fordrop.drop(bind, checkfirst=True)
    user_type_enum_fordrop.drop(bind, checkfirst=True)
    report_content_type_enum_fordrop.drop(bind, checkfirst=True)
    report_status_enum_fordrop.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
