"""Initial migration with User, Post, UserInterest, InviteCode models

Revision ID: 496fe7708328
Revises: 
Create Date: 2025-04-30 18:41:47.211812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496fe7708328'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invites_left', sa.Integer(), nullable=False, server_default='3'))
        batch_op.add_column(sa.Column('used_invite_code', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('used_invite_code')
        batch_op.drop_column('invites_left')

    # ### end Alembic commands ###
