"""Add privacy to Ampersound model

Revision ID: 5a687c4bd593
Revises: ca7121edf4ac
Create Date: 2025-05-06 06:53:20.422805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a687c4bd593'
down_revision = 'ca7121edf4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ampersound', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy', sa.String(length=50), nullable=False, server_default='public'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ampersound', schema=None) as batch_op:
        batch_op.drop_column('privacy')

    # ### end Alembic commands ###
