"""Add profile_picture to User model

Revision ID: 687f5c4e327a
Revises: db6255c5df38
Create Date: 2025-05-05 22:58:30.106055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687f5c4e327a'
down_revision = 'db6255c5df38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
