"""Use classification_scores JSON, remove score float

Revision ID: a798efd75054
Revises: 2264d7975933
Create Date: 2025-05-03 20:12:16.499536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a798efd75054'
down_revision = '2264d7975933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification_scores', sa.JSON(), nullable=True))
        batch_op.drop_index('ix_post_score')
        batch_op.drop_column('image_classification')
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('image_classification', sqlite.JSON(), nullable=True))
        batch_op.create_index('ix_post_score', ['score'], unique=False)
        batch_op.drop_column('classification_scores')

    # ### end Alembic commands ###
