"""empty message

Revision ID: aa7f6e64c31b
Revises: e2afb0285621
Create Date: 2025-05-08 12:52:48.406068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7f6e64c31b'
down_revision = 'e2afb0285621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ampersound', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='ampersoundstatus'), nullable=False, server_default='PENDING_APPROVAL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ampersound', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
