"""Add parent_post_id for tracking remixed images

Revision ID: add_parent_post_id
Revises: aa7f6e64c31b
Create Date: 2025-07-06 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_parent_post_id'
down_revision = 'aa7f6e64c31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_post_parent_post', 'post', ['parent_post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_parent_post', type_='foreignkey')
        batch_op.drop_column('parent_post_id')

    # ### end Alembic commands ###