"""Simplify User-InviteCode used relationship

Revision ID: b9f1d7f3368c
Revises: 0e2ad4779bba
Create Date: 2025-05-06 02:03:41.765058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f1d7f3368c'
down_revision = '0e2ad4779bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_used_invite_code_id', type_='unique')
        batch_op.drop_constraint('fk_user_used_invite_code_id', type_='foreignkey')
        batch_op.drop_column('used_invite_code_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_invite_code_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_used_invite_code_id', 'invite_code', ['used_invite_code_id'], ['id'])
        batch_op.create_unique_constraint('uq_user_used_invite_code_id', ['used_invite_code_id'])

    # ### end Alembic commands ###
