"""Add play_count to Ampersound model

Revision ID: ca7121edf4ac
Revises: 0f2addf57b0f
Create Date: 2025-05-06 05:09:42.040732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7121edf4ac'
down_revision = '0f2addf57b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ampersound', schema=None) as batch_op:
        batch_op.add_column(sa.Column('play_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_ampersound_play_count'), ['play_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ampersound', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ampersound_play_count'))
        batch_op.drop_column('play_count')

    # ### end Alembic commands ###
