"""Implmenet multi-category post scoring

Revision ID: cef81b5cdf11
Revises: 496fe7708328
Create Date: 2025-04-30 18:57:59.844216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef81b5cdf11'
down_revision = '496fe7708328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_category_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'category', name='uq_post_category_score')
    )
    with op.batch_alter_table('post_category_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_category_score_category'), ['category'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_category')
        batch_op.drop_column('category')

    with op.batch_alter_table('user_interest', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_interest_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_interest_category'))
        batch_op.alter_column('score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.create_index('ix_post_category', ['category'], unique=False)

    with op.batch_alter_table('post_category_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_category_score_category'))

    op.drop_table('post_category_score')
    # ### end Alembic commands ###
