"""Add privacy field to Post model

Revision ID: db0b9244e094
Revises: 500829234cc8
Create Date: 2025-05-03 23:54:03.263062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0b9244e094'
down_revision = '500829234cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add column as nullable first
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy', sa.Enum('PUBLIC', 'FRIENDS', name='postprivacy'), nullable=True))
    
    # Step 2: Set default value for existing rows
    op.execute("UPDATE post SET privacy = 'PUBLIC'")
    
    # Step 3: Make column non-nullable
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('privacy', nullable=False, existing_type=sa.Enum('PUBLIC', 'FRIENDS', name='postprivacy'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('privacy')

    # ### end Alembic commands ###
