name: Python Flask and React CI

on:
  push:
    branches: [ main ] # Adjust if your main branch is named differently (e.g., master)
  pull_request:
    branches: [ main ] # Adjust if your main branch is named differently

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # You can define specific versions or use a matrix for multiple versions
    strategy:
      matrix:
        python-version: ['3.9',]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Backend (Python/Flask) Steps
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # TODO: Verify and set your project's Python version
        cache: 'pip' # Optional: Caches pip dependencies to speed up future builds

    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backend tests (pytest)
      run: pytest
