name: PR Quick Check

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.py'
      - '**.js'
      - '**.jsx'
      - '**.json'
      - 'requirements.txt'
      - 'package*.json'

jobs:
  quick-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    # Quick checks
    - name: Python lint check
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

    - name: Frontend lint
      working-directory: ./frontend
      run: |
        npm ci
        npm run lint || true

    # Run only critical tests
    - name: Install backend dependencies
      run: |
        pip install -r requirements.txt

    - name: Run quick backend tests
      run: |
        pytest tests/test_app.py -v || true

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build